# Generated by Django 3.2.5 on 2022-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.CharField(max_length=20),
        ),
    ]
